tp=(10,20,30,40,"hello",4.5,True,10,20,30)
print(tp)
print(type(tp))
fruit=("orange","apple")
car=(1,"alto",2,"benz",3,"audi")
print(fruit)
print(car)
print(len(car))
car=car+(fruit)
print(car)
print(car+fruit)
t=(10,20,30)
print(sum(t))
del t 
print(t)